/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import control.Control;
import excepciones.NegocioException;
import javax.swing.JOptionPane;

/**
 *
 * @author katia
 */
public class PantallaInicio extends javax.swing.JFrame {

    /**
     * Creates new form PantallaInicio
     */
    public PantallaInicio() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnRegistrarPersonaYLicencia = new javax.swing.JButton();
        btnSolicitarPlaca = new javax.swing.JButton();
        btnConsultarHistorial = new javax.swing.JButton();
        btnInsercionMasiva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pantalla Inicio");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(880, 610));
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Ebrima", 1, 80)); // NOI18N
        lblTitulo.setText("Agencia Fiscal");

        btnRegistrarPersonaYLicencia.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrarPersonaYLicencia.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        btnRegistrarPersonaYLicencia.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarPersonaYLicencia.setText("Registrar Persona y Licencia");
        btnRegistrarPersonaYLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPersonaYLicenciaActionPerformed(evt);
            }
        });

        btnSolicitarPlaca.setBackground(new java.awt.Color(0, 0, 0));
        btnSolicitarPlaca.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        btnSolicitarPlaca.setForeground(new java.awt.Color(255, 255, 255));
        btnSolicitarPlaca.setText("Solicitar Placa");
        btnSolicitarPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarPlacaActionPerformed(evt);
            }
        });

        btnConsultarHistorial.setBackground(new java.awt.Color(0, 0, 0));
        btnConsultarHistorial.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        btnConsultarHistorial.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarHistorial.setText("Consultar historial");
        btnConsultarHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarHistorialActionPerformed(evt);
            }
        });

        btnInsercionMasiva.setBackground(new java.awt.Color(0, 0, 0));
        btnInsercionMasiva.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        btnInsercionMasiva.setForeground(new java.awt.Color(255, 255, 255));
        btnInsercionMasiva.setText("Insertar 20 personas con licencia");
        btnInsercionMasiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsercionMasivaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSolicitarPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsultarHistorial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInsercionMasiva)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnRegistrarPersonaYLicencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(lblTitulo)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblTitulo)
                .addGap(67, 67, 67)
                .addComponent(btnRegistrarPersonaYLicencia)
                .addGap(52, 52, 52)
                .addComponent(btnSolicitarPlaca)
                .addGap(48, 48, 48)
                .addComponent(btnConsultarHistorial)
                .addGap(44, 44, 44)
                .addComponent(btnInsercionMasiva)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarHistorialActionPerformed
        Control.getInstancia().mostrarPantallaConsultarHistorialPlacas();
        dispose();
    }//GEN-LAST:event_btnConsultarHistorialActionPerformed

    private void btnRegistrarPersonaYLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPersonaYLicenciaActionPerformed
        Control.getInstancia().mostrarPantallaRegistroPersonaYLicencia();
        dispose();
    }//GEN-LAST:event_btnRegistrarPersonaYLicenciaActionPerformed

    private void btnSolicitarPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarPlacaActionPerformed
        Control.getInstancia().mostrarPantallaMenuPlacas();
        dispose();
    }//GEN-LAST:event_btnSolicitarPlacaActionPerformed

    private void btnInsercionMasivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsercionMasivaActionPerformed
        try {
            Control.getInstancia().getPersonaBO().insertarMasivamentePersonasConLicencia(20);
            JOptionPane.showMessageDialog(this, "Se insertaron 20 personas con licencia correctamente.");
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "Error al insertar personas: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInsercionMasivaActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarHistorial;
    private javax.swing.JButton btnInsercionMasiva;
    private javax.swing.JButton btnRegistrarPersonaYLicencia;
    private javax.swing.JButton btnSolicitarPlaca;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
