/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import control.Control;
import dtos.PlacaDTO;
import excepciones.NegocioException;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author katia
 */
public class PantallaPlacasAutoNuevo extends javax.swing.JFrame {

    /**
     * Creates new form PantallaRegistroPersonaYLicencia
     */
    public PantallaPlacasAutoNuevo() {
        initComponents();
        String fechaEmision = LocalDate.now().toString();
        txtFechaEmision.setText(fechaEmision);
        txtFechaEmision.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblFechaEmision = new javax.swing.JLabel();
        lblNumSerie = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblLinea = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblRfc = new javax.swing.JLabel();
        txtFechaEmision = new javax.swing.JTextField();
        txtNumSerie = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtLinea = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtRfc = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        btnRegistrarPlaca = new javax.swing.JButton();
        txtColor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RegistroPersonaYLicencia");
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Ebrima", 1, 48)); // NOI18N
        lblTitulo.setText("Placas para automóvil nuevo");

        lblFechaEmision.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFechaEmision.setText("Fecha de emisión");

        lblNumSerie.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNumSerie.setText("Número de serie");

        lblMarca.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMarca.setText("Marca");

        lblLinea.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblLinea.setText("Línea");

        lblColor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblColor.setText("Color");

        lblModelo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblModelo.setText("Modelo");

        lblRfc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRfc.setText("RFC de la persona");

        btnAtras.setBackground(new java.awt.Color(0, 0, 0));
        btnAtras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnRegistrarPlaca.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrarPlaca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegistrarPlaca.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarPlaca.setText("Registrar Placa");
        btnRegistrarPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPlacaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaEmision)
                    .addComponent(lblNumSerie)
                    .addComponent(lblMarca)
                    .addComponent(lblLinea)
                    .addComponent(lblColor)
                    .addComponent(lblModelo)
                    .addComponent(lblRfc))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFechaEmision)
                    .addComponent(txtNumSerie)
                    .addComponent(txtMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(txtLinea, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(txtRfc, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(txtColor, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                .addContainerGap(226, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarPlaca)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitulo)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaEmision)
                    .addComponent(txtFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumSerie)
                    .addComponent(txtNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMarca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLinea))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblColor)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblModelo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRfc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRfc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAtras)
                            .addComponent(btnRegistrarPlaca))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPlacaActionPerformed
        try {
            PlacaDTO dto = new PlacaDTO();

            dto.setNumeroSerie(txtNumSerie.getText().trim());
            dto.setMarca(txtMarca.getText().trim());
            dto.setLinea(txtLinea.getText().trim());
            dto.setColor(txtColor.getText().trim());
            dto.setModelo(Integer.parseInt(txtModelo.getText().trim()));
            String rfc = txtRfc.getText().trim();

            PlacaDTO registrada = Control.getInstancia().registrarPlacaAutoNuevo(dto, rfc);

            JOptionPane.showMessageDialog(this, "Placa registrada con éxito:\n" + registrada.getNumeroPlaca());

            limpiarCampos();
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error al registrar la placa.", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarPlacaActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Control.getInstancia().mostrarPantallaMenuPlacas();
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void limpiarCampos() {
        txtNumSerie.setText("");
        txtMarca.setText("");
        txtLinea.setText("");
        txtColor.setText("");
        txtModelo.setText("");
        txtRfc.setText("");
        txtFechaEmision.setText(LocalDate.now().toString());
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRegistrarPlaca;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblFechaEmision;
    private javax.swing.JLabel lblLinea;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNumSerie;
    private javax.swing.JLabel lblRfc;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtFechaEmision;
    private javax.swing.JTextField txtLinea;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNumSerie;
    private javax.swing.JTextField txtRfc;
    // End of variables declaration//GEN-END:variables
}
