/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import control.Control;

/**
 *
 * @author katia
 */
public class PantallaMenuPlacas extends javax.swing.JFrame {

    /**
     * Creates new form PantallaMenuPlacas
     */
    public PantallaMenuPlacas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnAutoNuevo = new javax.swing.JButton();
        btnAutoUsado = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MenuPlacas");
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Ebrima", 1, 80)); // NOI18N
        lblTitulo.setText("Placas");

        btnAutoNuevo.setBackground(new java.awt.Color(0, 0, 0));
        btnAutoNuevo.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        btnAutoNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnAutoNuevo.setText("Para automóvil nuevo");
        btnAutoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoNuevoActionPerformed(evt);
            }
        });

        btnAutoUsado.setBackground(new java.awt.Color(0, 0, 0));
        btnAutoUsado.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        btnAutoUsado.setForeground(new java.awt.Color(255, 255, 255));
        btnAutoUsado.setText("Para automóvil usado");
        btnAutoUsado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoUsadoActionPerformed(evt);
            }
        });

        btnAtras.setBackground(new java.awt.Color(0, 0, 0));
        btnAtras.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAutoNuevo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(313, 313, 313)
                            .addComponent(lblTitulo))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(301, 301, 301)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAutoUsado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(311, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblTitulo)
                .addGap(78, 78, 78)
                .addComponent(btnAutoNuevo)
                .addGap(64, 64, 64)
                .addComponent(btnAutoUsado)
                .addGap(69, 69, 69)
                .addComponent(btnAtras)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoNuevoActionPerformed
        Control.getInstancia().mostrarPantallaPlacasAutoNuevo();
        this.dispose();
    }//GEN-LAST:event_btnAutoNuevoActionPerformed

    private void btnAutoUsadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoUsadoActionPerformed
        Control.getInstancia().mostrarPantallaPlacasAutoUsado();
        this.dispose();
    }//GEN-LAST:event_btnAutoUsadoActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Control.getInstancia().mostrarPantallaInicio();
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnAutoNuevo;
    private javax.swing.JButton btnAutoUsado;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
