/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import com.github.lgooddatepicker.components.DatePicker;
import control.Control;
import dtos.LicenciaDTO;
import dtos.PersonaDTO;
import enums.Duracion;
import excepciones.NegocioException;
import javax.swing.JOptionPane;

/**
 *
 * @author katia
 */
public class PantallaRegistroPersonaYLicencia extends javax.swing.JFrame {    
    DatePicker datePickerNacimiento;
    /**
     * Creates new form PantallaRegistroPersonaYLicencia
     */
    public PantallaRegistroPersonaYLicencia() {
        initComponents();
        configurarDateP();
        
        cmbDuracionLicencia.removeAllItems();
        cmbDuracionLicencia.addItem("UNO");
        cmbDuracionLicencia.addItem("DOS");
        cmbDuracionLicencia.addItem("TRES");
    }
    
    private void configurarDateP() {
        if (datePickerNacimiento == null) {
            datePickerNacimiento = new com.github.lgooddatepicker.components.DatePicker();
            datePickerNacimiento.setBounds(txtFechaNacimiento.getBounds());
            this.getContentPane().remove(txtFechaNacimiento);
            this.getContentPane().add(datePickerNacimiento);
            this.getContentPane().revalidate();
            this.getContentPane().repaint();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidoP = new javax.swing.JLabel();
        lblApellidoM = new javax.swing.JLabel();
        lblRfc = new javax.swing.JLabel();
        lblFechaNac = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblDuracionLicencia = new javax.swing.JLabel();
        lblCostoLicencia = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtRfc = new javax.swing.JTextField();
        txtFechaNacimiento = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCostoLicencia = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        btnRegistrarPersonaYLicencia = new javax.swing.JButton();
        cmbDuracionLicencia = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RegistroPersonaYLicencia");
        setPreferredSize(new java.awt.Dimension(880, 610));
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Ebrima", 1, 48)); // NOI18N
        lblTitulo.setText("Registro Persona y Licencia");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombre.setText("Nombre");

        lblApellidoP.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblApellidoP.setText("Apellido Paterno");

        lblApellidoM.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblApellidoM.setText("Apellido Materno");

        lblRfc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRfc.setText("RFC");

        lblFechaNac.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFechaNac.setText("Fecha nacimiento");

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTelefono.setText("Telefono");

        lblDuracionLicencia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDuracionLicencia.setText("Duración licencia (años)");

        lblCostoLicencia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCostoLicencia.setText("Costo licencia");

        txtCostoLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoLicenciaActionPerformed(evt);
            }
        });

        btnAtras.setBackground(new java.awt.Color(0, 0, 0));
        btnAtras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnRegistrarPersonaYLicencia.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrarPersonaYLicencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegistrarPersonaYLicencia.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarPersonaYLicencia.setText("Registrar Persona y Licencia");
        btnRegistrarPersonaYLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPersonaYLicenciaActionPerformed(evt);
            }
        });

        cmbDuracionLicencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDuracionLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDuracionLicenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblApellidoP)
                            .addComponent(lblApellidoM)
                            .addComponent(lblRfc)
                            .addComponent(lblFechaNac)
                            .addComponent(lblTelefono)
                            .addComponent(lblDuracionLicencia)
                            .addComponent(lblCostoLicencia))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtApellidoP)
                            .addComponent(txtApellidoM)
                            .addComponent(txtRfc, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(txtCostoLicencia, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(txtNombre)
                            .addComponent(cmbDuracionLicencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(lblTitulo)))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarPersonaYLicencia)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitulo)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoP)
                    .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoM)
                    .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRfc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRfc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaNac))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDuracionLicencia)
                    .addComponent(cmbDuracionLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCostoLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCostoLicencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtras)
                    .addComponent(btnRegistrarPersonaYLicencia))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbDuracionLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDuracionLicenciaActionPerformed
        String duracion = (String) cmbDuracionLicencia.getSelectedItem();
        if (duracion != null) {
            switch (duracion) {
                case "UNO":
                    txtCostoLicencia.setText("500");
                    break;
                case "DOS":
                    txtCostoLicencia.setText("900");
                    break;
                case "TRES":
                    txtCostoLicencia.setText("1200");
                    break;
                default:
                    txtCostoLicencia.setText("");
            }
        }
    }//GEN-LAST:event_cmbDuracionLicenciaActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Control.getInstancia().mostrarPantallaInicio();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnRegistrarPersonaYLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPersonaYLicenciaActionPerformed
        try {
            PersonaDTO persona = new PersonaDTO();
            persona.setNombre(txtNombre.getText().trim());
            persona.setApellidoPaterno(txtApellidoP.getText().trim());
            persona.setApellidoMaterno(txtApellidoM.getText().trim());
            persona.setRfc(txtRfc.getText().trim());
            persona.setTelefono(txtTelefono.getText().trim());
            persona.setFechaNacimiento(datePickerNacimiento.getDate());

            LicenciaDTO licencia = new LicenciaDTO();
            licencia.setCosto(Double.parseDouble(txtCostoLicencia.getText().trim()));
            licencia.setDuracion(Duracion.valueOf(cmbDuracionLicencia.getSelectedItem().toString()));

            Control.getInstancia().registrarPersonaYLicencia(persona, licencia);

            JOptionPane.showMessageDialog(this, "Registro exitoso.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de negocio", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Datos inválidos o faltantes.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarPersonaYLicenciaActionPerformed

    private void txtCostoLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoLicenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoLicenciaActionPerformed

    private void limpiarCampos() {
        txtNombre.setText("");
        txtApellidoP.setText("");
        txtApellidoM.setText("");
        txtRfc.setText("");
        txtTelefono.setText("");
        txtCostoLicencia.setText("");
        datePickerNacimiento.clear();
        cmbDuracionLicencia.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRegistrarPersonaYLicencia;
    private javax.swing.JComboBox<String> cmbDuracionLicencia;
    private javax.swing.JLabel lblApellidoM;
    private javax.swing.JLabel lblApellidoP;
    private javax.swing.JLabel lblCostoLicencia;
    private javax.swing.JLabel lblDuracionLicencia;
    private javax.swing.JLabel lblFechaNac;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRfc;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCostoLicencia;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRfc;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
